CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [AuthId] NVARCHAR(128) NOT NULL, 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GetUTCDate(), 
    [UpdatedAt] DATETIME2 NULL
)
